### Gateway alive
GET localhost:7001/alive
Accept: application/json

### Users alive
GET localhost:7002/alive
Accept: application/json

### Get All Users
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_list",
  "data": {}
}

### Get User by id
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_by_id",
  "data": {
    "id": 4
  }
}

### Error wrong user ID
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_by_id",
  "data": {
    "id": 100000
  }
}

### Create user
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_create",
  "data": {
    "username": "dedhasan",
    "first_name": "Aslan",
    "last_name": "Usoyan",
    "email": "dedhasan@lhvs.gr"
  }
}

### Update user
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_update",
  "data": {
    "id": 4,
    "username": "yaponchik",
    "first_name": "Vyacheslav",
    "last_name": "Ivankov",
    "email": "yaponchik@lhvs.gr"
  }
}
