### Gateway alive
GET localhost:7001/alive
Accept: application/json

### Users alive
GET localhost:7002/alive
Accept: application/json

### Get All Users
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_list",
  "data": {
    "id": 1
  }
}

### Get user by id
POST http://localhost:7001/
Content-Type: application/json

{
  "service": "users",
  "action": "user_by_id",
  "data": {
    "id": 1
  }
}
