services:
  nats-server:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks: ["nats-network"]

  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-server:6222"
    networks: ["nats-network"]
    depends_on: ["nats-server"]

  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-server:6222"
    networks: ["nats-network"]
    depends_on: ["nats-server"]

networks:
  nats-network:
    name: nats-network
