name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./path-to-your-Dockerfile
        push: true
        tags: yourdockerhubusername/yourappname:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kubernetes context
      uses: azure/setup-kubectl@v1
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f your-k8s-manifest.yml
